### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 2492: ordinal not in range(128)

### ISSUE THREAD

**Issue by anoopsanal** [FelixKrueger/TrimGalore#158]
I am using Trimgalore 0.6.7 from galaxy environment and getting the following error, it would grateful if anyone can help me on this.
Traceback (most recent call last):
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/lib/galaxy/jobs/runners/__init__.py", line 538, in _finish_or_resubmit_job
    self.sa_session.flush()
  File "<string>", line 2, in flush
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    _emit_update_statements(
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1000, in _emit_update_statements
    c = connection._execute_20(
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2030, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/mnt/gpfs1/home/scgalaxy01/galaxy_22_01/galaxy/.venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
UnicodeEncodeError: 'ascii' codec can't encode character '\xb5' in position 2492: ordinal not in range(128)

**Comment by anoopsanal** [comment]
ok thanks
